words2025 = [
    "SEXIEPBVAFTERBURNERL",  # 1
    "WTYZJAELVUENAWOPGHJV",  # 2
    "INRSEWQTPBBNRKEALSFE",  # 3
    "MSNAEGHIUEPAAXJEJHLN",
    "MZXVTRHQKRINTSEWQOIB",
    "LEXIOOBVBWBESMWQPCGP",
    "WCYZJUTLVUEIGWAPUHHV",
    "IWBSENAAPBMNNKENRSTE",
    "PIVBWDEONWQPIEPLPXEE",  # 9 reverse test
    "WLVZJSFOKKERTRIPLANE",
    "IDMDJUEALNEEOBSUEOGP",
    "MWNCAPHTOEUROXJEHHIN",
    "BEEHQPOIEBSEHQNPETNS",
    "JAIOEOSLXSEJSANLANEE",
    "MSXBVRHQKOTNLSEEROEB",
    "LEXRCTPEFREPNIWHTCRP",
    "WLYZJAELVUONIWOEGHJV",
    "INSPTAYNINHVILLAGENE",  # 18
    "MSNCEJHIOEPSLXORJHTN",  # 19
    "MZXBVEHMKOINBSETQOPB",  # 20
]
